### PR TITLE
Avoid assigning uninitialized local variable to itself

### LINKED ISSUE #114: DBD:Sybase - exec Test case failure due to cs_convert failed (to_numeric(3.2))
HI Team,

While testing the dbd sybase few test cases are failing for datatype – Numeric and Decimal. Please let me know if we are missing any sybase lib which does this conversion.

exec.t test case: Decimal binding and Numeric datatype is having issue.

$dbh->do("if object_id('dbitest') is not NULL drop proc dbitest");
$rc = $dbh->do(qq{
create proc dbitest \@one varchar(20), \@two int, \**@three numeric(5,2**), \@four smalldatetime, \@five float output
as
    select \@one, \@two, \@three, \@four
    select * from master..sysprocesses

    return \@two
});

ok(defined($rc), "$rc (create proc)\n");

$sth = $dbh->prepare("exec dbitest \@one = ?, \@two = ?, \@three = ?, \@four = ?, \@five = ? output");
#$rc = $sth->execute("one", 2, 3.2, "jan 1 2001", 5.4);
ok(defined($sth), "prepare dbitest");
$sth->bind_param(1, "one");
$sth->bind_param(2, 2, SQL_INTEGER);
**$sth->bind_param(3, 3.2, SQL_DECIMAL);**
$sth->bind_param(4, "jan 1 2001");
$sth->bind_param(5, 5.4, SQL_FLOAT);
$rc = $sth->execute();

Note: Perl and DBI module was installed already 

- HandleSetErr err='19', errstr='cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.', state=undef, undef
       cs_convert failed (to_numeric(3.2), type=16, scale=1, precision=3, maxlen=35)
    !! ERROR: -1 'cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '3.2'' (err#1)
    <- execute= ( undef ) [1 items] at exec.t line 76

t/base.t ........ ok
t/exec.t ........ 1/25
#   Failed test 'execute dbitest 1'
#   at t/exec.t line 77.

#   Failed test 'exec dbitest 2'
#   at t/exec.t line 82.

#   Failed test 'exec dbitest 3'
#   at t/exec.t line 86.

#   Failed test 'out param 1'
#   at t/exec.t line 88.

#   Failed test 'execute fail mode 1'
#   at t/exec.t line 104.

#   Failed test 'execute fail mode 2'
#   at t/exec.t line 108.

#   Failed test 'execute fail mode 3'
#   at t/exec.t line 117.

#   Failed test 'execute fail mode 4'
#   at t/exec.t line 124.

#   Failed test 'execute fail mode 5'
#   at t/exec.t line 128.

#   Failed test 'execute fail mode 6'
#   at t/exec.t line 132.
# Looks like you planned 25 tests but ran 19.
# Looks like you failed 10 tests of 19 run.
t/exec.t ........ Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 16/25 subtests
t/fail.t ........ 1/12
#   Failed test 'execute w/placeholder'
#   at t/fail.t line 76.
# Looks like you failed 1 test of 12.
t/fail.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests
t/login.t ....... 1/6 DBD
[Sybase_dbd_failures.txt](https://github.com/mpeppler/DBD-Sybase/files/8711132/Sybase_dbd_failures.txt)
::Sybase::db ping failed: ct_cmd_alloc failed at t/login.t line 32.
t/login.t ....... ok
t/main.t ........ ok
t/multi_sth.t ... ok
t/nsql.t ........ ok
t/place.t ....... 1/19 DBD::Sybase::st execute failed: cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '222.333' at t/place.t line 39.

#   Failed test 'insert 1'
#   at t/place.t line 40.
DBD::Sybase::st execute failed: cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '2' at t/place.t line 47.

#   Failed test 'insert 2'
#   at t/place.t line 48.
ct_result(ct_dynamic(CS_PREPARE)) returned -205 at /home/UserID/04202022/DBD-Sybase-1.19/blib/lib/DBD/Sybase.pm line 135.
DBD::Sybase::db prepare failed: Server message number=208 severity=16 state=1 line=1 server=DS_CTO procedure=DBD2 text=#t not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).
  at t/place.t line 56.

#   Failed test 'prepare 2'
#   at t/place.t line 57.
Can't call method "execute" on an undefined value at t/place.t line 59.
# Looks like your test exited with 255 just after 12.
t/place.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 10/19 subtests
t/thread.t ...... skipped: this perl 5.034001 not configured to support iThreads
t/utf8.t ........ ok
t/xblk.t ........ ok
t/xblob.t ....... ok

Test Summary Report
-------------------
t/exec.t      (Wstat: 2560 Tests: 19 Failed: 10)
  Failed tests:  8-17
  Non-zero exit status: 10
  Parse errors: Bad plan.  You planned 25 tests but ran 19.
t/fail.t      (Wstat: 256 Tests: 12 Failed: 1)
  Failed test:  9
  Non-zero exit status: 1
t/place.t     (Wstat: 65280 Tests: 12 Failed: 3)
  Failed tests:  5, 10, 12
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 19 tests but ran 12.
Files=13, Tests=235,  2 wallclock secs ( 0.05 usr  0.01 sys +  0.65 cusr  0.12 csys =  0.83 CPU)
Result: FAIL
Failed 3/13 test programs. 14/235 subtests failed.
make: The error code from the last command is 255.

Env Variables 
UserID@UnixAIX7.1_Server:/home/UserID$ echo $SYBASE
/opt/sybase/sybase15
UserID@UnixAIX7.1_Server:/home/UserID$ echo $SYBASE_OCS
OCS-15_0.32bit
UserID@UnixAIX7.1_Server:/home/UserID$ echo $PERL5LIB
/home/UserID/perl5/opt/uxapps/perl5/lib/:/home/UserID/perl5/opt/uxapps/perl5/lib/site_perl/5.34.1/aix:/home/UserID/perl5/opt/uxapps/perl5/lib/site_perl/5.34.1:/home/UserID/perl5/opt/uxapps/perl5/lib/5.34.1/aix:/home/UserID/perl5/opt/uxapps/perl5/lib/5.34.1

Sybase Lib
UserID@UnixAIX7.1_Server:/opt/sybase/sybase15/OCS-15_0.32bit/lib$ ls -l *.a
-rw-r--r--    1 sybase   sybase       210136 Aug 16 2011  libsybblk.a
-rw-r--r--    1 sybase   sybase       210482 Aug 16 2011  libsybblk_r.a
-rw-r--r--    1 sybase   sybase      1726875 Aug 16 2011  libsybcomn.a
-rw-r--r--    1 sybase   sybase      1762184 Aug 16 2011  libsybcomn_r.a
-rw-r--r--    1 sybase   sybase       154139 Aug 16 2011  libsybcs.a
-rw-r--r--    1 sybase   sybase       162103 Aug 16 2011  libsybcs_r.a
-rw-r--r--    1 sybase   sybase      1209283 Aug 16 2011  libsybct.a
-rw-r--r--    1 sybase   sybase      1216580 Aug 16 2011  libsybct_r.a
-rw-r--r--    1 sybase   sybase      2813610 Aug 16 2011  libsybdb.a
-rw-r--r--    1 sybase   sybase        78323 Aug 16 2011  libsybintl.a
-rw-r--r--    1 sybase   sybase        78249 Aug 16 2011  libsybintl_r.a
-rw-r--r--    1 sybase   sybase      1034819 Aug 16 2011  libsybsrv.a
-rw-r--r--    1 sybase   sybase      1072912 Aug 16 2011  libsybsrv_r.a
-rw-r--r--    1 sybase   sybase       389942 Aug 16 2011  libsybtcl.a
-rw-r--r--    1 sybase   sybase       401065 Aug 16 2011  libsybtcl_r.a
-rw-r--r--    1 sybase   sybase       635380 Aug 12 2011  libsybunic.a
[Sybase_dbd_failures.txt](https://github.com/mpeppler/DBD-Sybase/files/8711144/Sybase_dbd_failures.txt)

### PR DESCRIPTION
**Pull request by RyanHeule**
After expanding the ```LOCALE``` macro, the code expands to ```CS_LOCALE *locale = ((imp_dbh)->locale ? (imp_dbh)->locale : locale);```

When ```imp_dbh->locale``` is ```NULL```, this gives undefined behavior. On AIX, it is interpreted as assigning the local variable to itself (i.e. leaving it uninitialized).  It seems some compilers must be smart enough to realize the real intent, and accordingly copy the value of the global variable, which would explain why more people aren't experiencing the same issue.

Fixes #114.

### CODE REVIEW

File: dbdimp.c [hunk 1]
```diff
@@ -5422,7 +5422,6 @@ static int to_numeric(char *str, SV *sth, imp_sth_t *imp_sth, CS_DATAFMT *datafm
   CS_DATAFMT srcfmt;
   CS_INT reslen;
   char *p;
-  CS_LOCALE *locale = LOCALE(imp_dbh);
```
Comment (mpeppler) [inline dbdimp.c:5425]: Ah - now I get it. The problem really is that there is a global variable called "locale" as well, so the macro here is taking the wrong variable.
Ugh - really ugly....

Thanks!

**Comment by SurendarRajavel** [comment]
Hi Michael,

Can you please let us know, when we can expect new updated package.

Thanks Ryan for your help!!!

**Comment by mpeppler** [comment]
Hi Surender - a new DBD::Sybase package has just been released to CPAN.

Michael

**Comment by SurendarRajavel** [comment]
Hi Michael,
I have downloaded and installed DBD-Sybase-1.20 successfully. Test cases ran fine. Thanks a lot for your immediate response and actions.

Regards,
Surendar
